WeatherApp.Web/Controllers/FavoriteLocationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WeatherApp.Domain.DomainModels;
using WeatherApp.Repository.Data;
using WeatherApp.Service.Interfaces;

namespace WeatherApp.Web.Controllers
{
    [Authorize]
    public class FavoriteLocationsController : Controller
    {
        private readonly IFavoriteLocationService _favoriteLocationService;

        public FavoriteLocationsController(IFavoriteLocationService favoriteLocationService)
        {
            _favoriteLocationService = favoriteLocationService;
        }

        // GET: FavoriteLocations
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var favorites = await _favoriteLocationService.GetUserFavoritesAsync(userId);
            return View(favorites);
        }


        // GET: FavoriteLocations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FavoriteLocations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int locationId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if(!string.IsNullOrEmpty(userId))
            {
                await _favoriteLocationService.AddFavoriteAsync(userId, locationId);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        // GET: FavoriteLocations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var favorites = await _favoriteLocationService.GetUserFavoritesAsync(userId);
            var favorite = favorites.FirstOrDefault(f => f.Id == id);

            if (favorite == null)
            {
                return NotFound();
            }

            return View(favorite);
        }

        // POST: FavoriteLocations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _favoriteLocationService.RemoveFavoriteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WeatherApp.Web/Views/FavoriteLocations/Create.cshtml
@model WeatherApp.Domain.DomainModels.FavoriteLocation

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>FavoriteLocation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class ="form-control" asp-items="ViewBag.LocationId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WeatherApp.Web/Views/FavoriteLocations/Delete.cshtml
@model WeatherApp.Domain.DomainModels.FavoriteLocation

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FavoriteLocation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

WeatherApp.Web/Views/FavoriteLocations/Details.cshtml
@model WeatherApp.Domain.DomainModels.FavoriteLocation

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>FavoriteLocation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

WeatherApp.Web/Views/FavoriteLocations/Edit.cshtml
@model WeatherApp.Domain.DomainModels.FavoriteLocation

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>FavoriteLocation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class="form-control" asp-items="ViewBag.LocationId"></select>
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WeatherApp.Web/Views/FavoriteLocations/Index.cshtml
@model IEnumerable<WeatherApp.Domain.DomainModels.FavoriteLocation>

@{
    ViewData["Title"] = "My Favorite Locations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewData["Title"]</h2>

@if (!Model.Any())
{
    <p>No favorite locations yet.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Location Name</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Location?.Name</td>
                    <td>@item.Location?.Latitude</td>
                    <td>@item.Location?.Longitude</td>
                    <td>
                        <form asp-action="Delete" asp-controller="FavoriteLocations" method="post">
                            <input type="hidden" name="id" value="@item.Id" />
                            <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}